bh-1001 text scaling fix
codeRIT/brickhack.io pull request #1005
Opened 2020-12-10 20:58 UTC by sjv01180

2020-12-10 23:41 UTC, peterkos requested changes
Doesn't quite work :c 

Also please remove the `sass/.main.scss.swp` and `.index.html.swp` files! 

<img width="1544" alt="Screen Shot 2020-12-10 at 6 41 48 PM" src="https://user-images.githubusercontent.com/2782749/101843043-5d44ab00-3b17-11eb-8b45-0ca1fe75bd65.png">

2020-12-10 23:41 UTC, peterkos commented on sass/main.scss
> +            margin-top: -217px;
Arbitrary number here -- could you use something more like `-200px`? 
However this still clips on my 16" mac, making the window sightly narrower.

2020-12-10 23:41 UTC, peterkos commented on sass/main.scss
> +            width: 57%;
Width of the other div in the flex container wasn't adjusted -- also `57%` seems arbitrary

2020-12-10 23:41 UTC, peterkos commented on sass/main.scss
> +
nit: no added newlines here

2020-12-11 03:45 UTC, sjv01180 commented
Made some changes to the left padding on the hero id for supporting smaller laptop screens. 

If this works, we should consider adding additional variables for each screen size. This would give us a head start towards responsive web design.

2020-12-11 05:22 UTC, peterkos approved these changes
Great work Sam!

I've gone in and made a couple tweaks to better fit our design. You're absolutely right and we should definitely have vars for breakpoints -- I'm still trying to figure out the best way to plan adding mobile support (i.e., section-by-section, or just having it be done in blocks of work)

2020-12-11 05:23 UTC, merged