Navbar + Footer fixes
codeRIT/brickhack.io pull request #1044
Opened 2020-12-14 05:23 UTC by ww2497

resolves #1032

2020-12-14 06:26 UTC, ww2497 commented
Unsure about what the BH logo stuff mentioned in the issue is referring to

2020-12-14 08:37 UTC, peterkos commented
I'll give a review in the morning!

2020-12-15 04:14 UTC, peterkos requested changes
Great work! Couple small changes.

2020-12-15 04:14 UTC, peterkos commented on sass/main.scss
> +            padding: 0 5px;
Good catch on the padding here! Although style-wise, lets add units to the `0` to keep it inline with the `px` on the right:
```suggestion
            padding: 0px 5px;
```
(rest of stylesheet follows this convention, aside when unit is undefined, like for `marign: 0 auto;`)

2020-12-15 04:14 UTC, peterkos commented on index.html
> +                <p>
(for all lines in this PR where applicable)

2020-12-15 04:14 UTC, peterkos commented on sass/main.scss
> +        display: flex;
I like this solution 😄

2020-12-15 04:23 UTC, ww2497 commented on sass/main.scss
> +            font-size: 0.95em;
0.95 matches the design more closely with the 'contact us' and 'hello@coderit.org' text having similar widths, but I suppose this is fine

2020-12-15 04:31 UTC, peterkos approved these changes
LGTM :shipit:

2020-12-15 04:31 UTC, merged