Update ricky hero svgs to use the ones on Notion, adjust color of site
codeRIT/brickhack.io pull request #1138
Opened 2021-01-31 05:53 UTC by sjv01180

2021-01-31 07:08 UTC, peterkos requested changes
Changes look good overall, but pls make sure to update your `node` version is 15 or greater! 

Delete the `package-lock.json`, update node, and re-run `npm install`; there should be no changes to the `package-lock.json` after

2021-01-31 21:15 UTC, sjv01180 reviewed
Changed package-lock with a more recent nodejs version. Shoutout to my coop for insisting on limiting nodejs to 6.8.0

2021-01-31 21:53 UTC, peterkos commented
@sjv01180 Can you also follow the steps above of deleting package-lock, `npm install`, then re-commit?

2021-02-04 05:09 UTC, peterkos requested changes
one nit!

2021-02-04 05:09 UTC, peterkos commented on index.js
> +});
```suggestion
});

```
nit: newline end of file

2021-02-06 04:43 UTC, peterkos approved these changes
🎉

2021-02-06 04:44 UTC, merged