Footer hover effect
codeRIT/brickhack.io pull request #1152
Opened 2021-02-07 04:38 UTC by ww2497

resolves #1093

2021-02-09 05:49 UTC, peterkos requested changes
Nice change!
Although can we have the links on hover change to `$red` insteaad of transforming? Transforms might look better under block elements and we can use color for inline; I'm planning the same thing for the updated schedule design and is what the current schedule uses but a bit less

2021-02-09 05:49 UTC, peterkos commented on index.html
> +                    |
Can the `|` be wrapped in a `p` tag?

2021-02-11 06:51 UTC, ww2497 commented
> Nice change!
> Although can we have the links on hover change to `$red` insteaad of transforming? Transforms might look better under block elements and we can use color for inline; I'm planning the same thing for the updated schedule design and is what the current schedule uses but a bit less

Alright, I'll see how that effect looks. I did the translate effect because that's apparently what design wanted according to the issue.

2021-02-13 07:43 UTC, peterkos requested changes
One other tweak: Translate effect for logos should be put back -- having logos change color on hover is a branding guideline issue!

2021-02-13 07:43 UTC, peterkos commented on index.html
> +                    <span>|</span>
Oh wait, I see, this is all wrapped in `p`, the `span` isnt needed! My b

2021-02-13 07:43 UTC, peterkos commented on sass/main.scss
> +            &:hover {
nit: `&:` styles should go above any other nested CSS, so this should go above the `i` above

2021-02-18 07:05 UTC, peterkos approved these changes
LGTM!

2021-02-19 06:16 UTC, merged